export default {
   NEXT_PUBLIC_FIREBASE_APP_ID: 'G-XRNVVSWYSN',
   NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '938815335796',
   NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'dvr-notes-mw02.firebasestorage.app',
   NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'dvr-notes-mw02',
   NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyDG7_I7WbNrZW9gk5dDxEkcJ-oZK3xrYck',
   NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'dvr-notes-mw02.firebaseapp.com'
};
